### ISSUE TITLE
Compatibility Issue with Immersive Engineering on 1.16.5

### ISSUE THREAD

**Issue by Nocturnus13** [aurilisdev/Ballistix#77]
When I try to load into a world with the latest versions of Ballistix, Electrodynamics, and Immersive Engineering on 1.16.5, the game crashes, giving me the following error.

I know that 1.16.5 isn't your priority with so many more recent versions, however I would appreciate if you would take the time to consider finding a solution to this error. If not it is understandable, and have a great day.

```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 17/11/24 23:30
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at blusunrize.immersiveengineering.client.ClientProxy.onWorldLoad(ClientProxy.java:444) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.common.EventHandler.onLoad(EventHandler.java:97) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_80_EventHandler_onLoad_Load.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3349/313907874.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:379) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:308) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:60) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$6742/37123772.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 27884506264 bytes (26592 MB) / 33353105408 bytes (31808 MB) up to 34359738368 bytes (32768 MB)
	CPUs: 12
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx32G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.42.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.42.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.42.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.42.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.42.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.42
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.42-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		Ballistix-1.16.5-0.3.1-0.jar                      |Ballistix                     |ballistix                     |1.16.5-0.3.1-0      |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.42-universal.jar                |Forge                         |forge                         |36.2.42             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		ImmersiveEngineering-1.16.5-5.1.0-148.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.1.0-148    |DONE      |Manifest: NOSIGNATURE
		Electrodynamics-1.16.5-0.5.1-0.jar                |Electrodynamics               |electrodynamics               |1.16.5-0.5.1-0      |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: cc7dfdd3-d3b4-41d7-947b-17114d6d231b
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:forge, mod:ballistix, mod:electrodynamics, mod:immersiveengineering
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
```

**Comment by skiprocks999** [comment]
1.16.5 is borderline abandonware at this point sadly. There could be so many causes of this crash, and I would have zero support from forge if I can't find the problem. You're more than welcome to submit a PR for the fix.
